name = "claw-bot-cloudflare"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

# KV namespace for skills storage
[[kv_namespaces]]
binding = "KV_SKILLS"
id = "6717aa4238004db28d8850eeab69d76e"

[[d1_databases]]
binding = "DB_MEMORY"
database_name = "claw-memory"
database_id = "96b90725-97e4-4af5-9b7d-16e5fa1fcc1f"

# Cron triggers
[triggers]
crons = ["*/5 * * * *"]

# Variables
[vars]
LLM_PROVIDER = "iflow"
IFLLOW_API_KEY = "sk-17503aef4a609b2cb14618ab6a452355"
ADMIN_USERNAME = "ericlx"
ADMIN_PASSWORD = "bb5201314lx"
